### ISSUE TITLE
[5] Write document about Airflow migration

### ISSUE THREAD

**Issue by Isaiah-Turner** [stellar/stellar-etl-airflow#22]
### What
We need a document that details the process of moving from Hubble to Airflow. It will discuss when we intend to deprecate Hubble, what the challenges are, and anything that could impede deployment.

### Why
We want to have a solid plan for migration and a good idea of what challenges will face us. This document will help with both of those.

**Comment by debnil** [comment]
Thanks for initiating this process! It's important that we do this well without compromising mission-critical data infrastructure.

We need to decide the relationship between the SDF-maintained dataset and the Google PDP's, and whether we will continue to maintain our public/private [dogfooding](https://newrepublic.com/article/115349/dogfooding-tech-slang-working-out-glitches) procedure. We currently write to the publicly exposed `crypto_stellar.crypto_stellar` dataset, and then copy that written dataset to the `hubble-*.crypto_stellar` dataset. I see a few different options:
1) We continue to operate this procedure separately from the PDP deployment
2) We use the PDP deployment as public, and read from it to a private dataset for internal analytics

I believe that we're doing 1, but want to confirm that before we plan a fuller migration. @nikhilsaraf @accordeiro

**Comment by nikhilsaraf** [comment]
Both #1 and #2 sound the same to me, I think I'm missing the finer difference, can you elaborate @debnil?

**Comment by debnil** [comment]
@nikhilsaraf: Sorry about the late reply, just saw this. We talked about this on a sync earlier this week and decided 1 is the right approach, but good to write down and answer the question. The difference is whether or not SDF runs the ETL tooling:
- 1 means that SDF maintains both a public and private dataset, on our own infrastructure and using our own deployment of this ETL tooling. Google also runs it separately, and hosts their own dataset. There is no dependency between our dataset and Google's.
- 2 means that only Google PDP deploys our tooling, and our internal dataset updates through copying changes to the PDP dataset. In other terms, we don't run the ETL ourselves, we just read changes from the PDP. There is full dependency on Google for our internal operations. As discussed, this has low to zero visibility/observability, and it offloads debugging to an external organization for important internal business metrics.

**Comment by Isaiah-Turner** [comment]
I created a document about this process [here](https://docs.google.com/document/d/1FyHsUdIsE7EidLzsjubdOPmZdbaCFx7P9_fU4X3G8Og/edit?usp=sharing).
