### ISSUE TITLE
[1] Benchmark memory usage

### ISSUE THREAD

**Issue by debnil** [stellar/stellar-etl-airflow#29]
**What**
We should benchmark memory usage, including for both catch-up and a single snapshot update.

**Why**
This will give ballpark figures that help them ensure quality of deployment.

**Comment by Isaiah-Turner** [comment]
### Single snapshot
I'm getting these numbers from looking at the files I have in Google Cloud Storage. I'm not sure if BigQuery makes space optimizations that would result in a lower table size.
- Accounts: 
    - Average is 550 KB
    - Max is 1.6 MB
    - Min is 356 KB
- Ledgers: 
    - Always roughly 57 KB
- Offers: 
    - Average is 294 KB
    - Max is 37 KB
    - Min is 87 KB
- Trustlines: 
    - Average is 153 KB
    - Max is 177 KB
    - Min is 119 KB
- Transactions: 
    - Early on there aren’t any
    - Around 500 KB on average later
- Operations: 
    - Early on there are none
    - Around 4 MB on average later
- Trades: 
    - Early on there are none
    - Around 90 KB on average later

Overall, each checkpoint should be around 5.6 MB of uploaded data.

### Whole dataset
Looking at the Hubble tables as they are now:
- Accounts: 684 MB (+ 617 MB for history accounts)
- Ledgers: 17.51 GB
- Offers: 10.42 MB
- Trustlines: 729.97 MB
- Transactions: 151.33 GB
- Operations: 429.07 GB
- Trades: 2.13 GB
- Enriched history operations: 1.03 TB

**Comment by debnil** [comment]
Great! I don't believe there are any space optimizations between BigQuery and Google Cloud Storage, and I can't find any evidence indicating those exist.
