### ISSUE TITLE
[1] Set up Cloud Composer

### ISSUE THREAD

**Issue by debnil** [stellar/stellar-etl-airflow#30]
**What**
We need to set up [Cloud Composer](https://cloud.google.com/composer) to deploy and orchestrate our Airflow pipeline. I assume that Google PDP will use their own composer setup, but we should do this to test deployment and be able to run this pipeline internally.

**Comment by Isaiah-Turner** [comment]
Initial setup is done. See #34 for the issue that updates documentation, and #35 for testing/finalization of the world done in this issue.
