### ISSUE TITLE
[6] Airflow knowledge share

### ISSUE THREAD

**Issue by Isaiah-Turner** [stellar/stellar-etl-airflow#38]
### What
We need to ensure the Voyager team is knowledgeable about Airflow and how Stellar uses it.

### Why
Once Isaiah's internship ends, we want to still have a good amount of knowledge about Airflow so that the team can continue maintenance or development.

### Where

Readme for this Repo

**Comment by debnil** [comment]
Two questions:
1) What do we think are major shortcomings now? While I don't know Airflow as a technology well, Isaiah's [README](https://github.com/stellar/stellar-etl-airflow) is excellent. It details setup and repo structure with deep and precise detail. I'm not sure what resources are missing, but very open to ideas.

2) What do we think the best structure for this is? A meet, a Google doc, extending the above README? This is closely tied to the above question.

**Comment by nikhilsaraf** [comment]
I think the ball is in our court (you and me) to learn about Airflow from the various resources already documented, and then hold a meeting if necessary so we can discuss anything that may not be clear to us.

The deliverable for this task if for one of us (you or I, or both) to be able to demo a local copy of the airflow system and/or demonstrate expertise in the handling of our production system. There's certain context in the production ops that Isaiah probably has which you and I should become knowledgeable in that is more likely code related than ops related. We are not looking to gain the knowledge that the ops team already has around our Airflow deployment.
