### ISSUE TITLE
Some files contain hardcoded paths to local schema files

### ISSUE THREAD

**Issue by medvedev1088** [stellar/stellar-etl-airflow#49]
In some places the paths point to local file system, e.g. https://github.com/stellar/stellar-etl-airflow/blob/master/dags/stellar_etl_airflow/build_apply_gcs_changes_to_bq_task.py#L35

Also it seems `factEvent_Schema.json` file is missing.

**Comment by medvedev1088** [comment]
@Isaiah-Turner could you please take a look at this?

**Comment by Isaiah-Turner** [comment]
@medvedev1088 Sorry about that! This should be fixed now. I added a new variable called `schema_filepath` in #50.
