### ISSUE TITLE
big query dataset tables have a "_table" suffix

### ISSUE THREAD

**Issue by acharb** [stellar/stellar-etl-airflow#70]
This might be something that google-cloud-bigquery==1.27.2 might set by default. But if not it's a repetitive suffix we don't need

**Comment by sydneynotthecity** [comment]
Fix: update the table name in the Airflow variables.txt file. The file that is in the Airflow Admin UI is the source of truth. 

Note: the `_table` suffix was added to the Helix version of the codebase to align with other Blockchain datasets. Internally we should drop the `*_table` convention to align with internal datasets but leave Helix's alone.
