### ISSUE TITLE
some data windows are getting skipped

### ISSUE THREAD

**Issue by acharb** [stellar/stellar-etl-airflow#71]
when looking at the big query datasets it looks like the gcp_airfow_internal one is missing a good chunk of data. Looks like some of the data isn't getting uploaded from airflow even though it should
eg.:
2015-10-04 21:00:00 - 23:00:00 [shows empty for big query](https://console.cloud.google.com/bigquery?project=hubble-261722&ws=!1m8!1m2!2m1!1scrypto-stellar!1m4!4m3!1shubble-261722!2scrypto_stellar_internal!3shistory_ledgers&j=bq:US:bquxjob_1be0e896_1796d532e51&page=queryresults) when it shouldn't be

([airflow logs at that timespan](https://rdfa8d47b3c53930ap-tp.appspot.com/admin/airflow/log?task_id=load_ledgers_to_gcs&dag_id=history_archive_export&execution_date=2015-10-04T21%3A00%3A00%2B00%3A00&format=json))

probably it's something to do with poststart.sh not moving the data .txt file

so
1. figure out why poststart.sh isn't moving the text file to be uploaded to big query and fix
2. if possible ensure airflow throws a "failure" in this situation so we're aware

**Comment by shanzzam** [comment]
@nikhilsaraf were you or @acharb going to address this? If not, I'll move back to the Backlog.

**Comment by acharb** [comment]
yup, tackling this this sprint

**Comment by acharb** [comment]
I've been keeping an eye on this ticket over the last week and it's not skipping windows anymore. The airflow project is almost halfway through 2019 w/o the error. Once it's caught all the way up to 2021 I'll check again

When this error initially arose it may have been because we were messing with the airflow time window configs (changed from every day, to every 3 hours) during the run. Keeping the window consistent at every 3 hours may be the fix

**Comment by sydneynotthecity** [comment]
Issue has been resolved. Windows get skipped because of the `poststart.sh` script truncating files before a full data load. We are not seeing this behavior anymore.
